### PR TITLE
Add back-end functionality for read status and notes

### PR DESCRIPTION
**Pull request by majinmilad**
Have added back read status and notes updating functionality inside of userBooks.ts

There are associated hooks for them as well at the bottom of the module. You can add a note or change read status for a book which has never been interacted with by the current user, it does not need to be in one of their shelves.

The useUserBookDetails (hook for getUserBookDetails) can be used to retrieve this data.

### CODE REVIEW

**Comment by majinmilad** [comment]
@electropicks if you can take a look at the hooks to see if they are correct I would appreciate it!

**Comment by electropicks** [comment]
rebased on main

**Review by electropicks — CHANGES_REQUESTED** [review]
approved once rebased with new add to shelf button

**Comment by majinmilad** [comment]
Seems to be a slight conflict in popup.tsx

**Comment by majinmilad** [comment]
Closed the PR. The changes present here we're successfully rebased and integrated into main but this branch is no longer being used and is behind.

**Pull request closed without merging**
